server:
  port: 80

spring:
  application:
    name: feignorder80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 6000

logging:
  level:
    com.zlw.springcloud.service.PaymentFeign: debug

feign:
  hystrix:
    enabled: true
