server:
  port: 8084


spring:
  application:
    name: payment
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.0.66:3306/app?relaxAutoCommit=true&amp;zeroDateTimeBehavior=convertToNull
    username: ydjw
    password: ydjw



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zlw.springcloud.entities  #实体类所在包


